"""
DO NOT EDIT - Auto-generated file
Generated by talon-manifest-generator v2.0.0

This file provides:
- Package version checking via ui_elements_version() action
"""
import json
import os
from talon import Module

mod = Module()

@mod.action_class
class Actions:
    def ui_elements_version() -> tuple[int, int, int]:
        """
        Returns the package version as (major, minor, patch).

        Usage: actions.user.ui_elements_version() >= (1, 2, 0)
        """
        manifest_path = os.path.join(os.path.dirname(__file__), 'manifest.json')
        with open(manifest_path, 'r', encoding='utf-8') as f:
            version_str = json.load(f)['version']
        return tuple(map(int, version_str.split('.')))
